#%RAML 1.0
title: Tokens
version: v1
mediaType: application/json
protocols: [ HTTPS ]

/tokens/{token}:
  put:
    description: Adds a new token
    body:
      application/json:
        example: |
          {
            "user": "brian@things.net",
            "state": "active",
            "count": 0
          }
    responses:
      200:
        description: The token was created

  get:
    description: Gets a token
    responses:
      200:
        headers:
          ETag:
            description: Unique tag of the state of the resource
            example: md5 sum of the token object
        body:
          application/json:
            example: |
              {
                "user": "brian@things.net",
                "state": "active",
                "count": 0
              }
      404:
        description: Token not found
  delete:
    description: Removes a token
    responses:
      200:
